{{- if .Values.experimental.kubernetesGateway.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GatewayClass
metadata:
  name: {{ .Values.experimental.kubernetesGateway.className }}
  labels:
    {{- include "traefik.labels" . | nindent 4 }}
spec:
  controllerName: {{ .Values.experimental.kubernetesGateway.controllerName }}
{{- end }}